config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/urls/new')
  resources :urls

end

app/models/url.rb
class Url < ActiveRecord::Base
	validates :original, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	def index
		@urls = Url.all
	end

	def show
		url = Url.where(:random_id => params[:id]).first
		if url
			redirect_to url.original
		else
			render "index"
		end
	end

# Creating the random string
	def new
		@url = Url.new

		letters = [('a'..'z'),('A'..'Z')].map { |l| l.to_a }.flatten
		@url.random_id = (0..8).map { letters[rand(letters.length)] }.join
		
	end

	def url_params
		params.require(:url).permit(:original, :random_id)
	end

	def create
		@url = Url.new(url_params)
		if @url.save
			redirect_to urls_path
		else
			render 'new'
		end
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
        <p>&copy; kodekorp  2014 | <%= link_to "ffdevelopment", "" %></p>
</div>

app/views/layouts/_header.html.erb
<div class="header">
        <ul class="nav nav-pills pull-right">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact</a></li>
        </ul>
        <h3 class="text-muted">shortyfyMe</h3>
</div>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortyfy | Basic url Shortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">
		<%= render 'layouts/header' %>

		<%= yield %>

		<%= render 'layouts/footer' %>
	</div>

</body>
</html>

app/views/urls/index.html.erb
<h1>Shortyfyed urls</h1>
<% @urls.each do |url| %>

<table class="table table-stripped">
	<thead>
		<tr>
			<th>Shortened URL</th>
			<th>Original URL</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<%= link_to url.random_id, url_path(:id => url.random_id) %>
			</td>
			<td>
				<%= url.original %>
			</td>
		</tr>
	</tbody>
	
</table>

<% end %>

<%= link_to "Shortyfy another url", new_url_path, class: "btn  btn-success" %>



<div class="row">
	<div class="col-md-4">
		<h2>Info here</h2>
		<p>
			Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. 
		</p>
		<p>
			<a class="btn btn-default" role="button" href="#">
			View details »

			</a>
		</p>
	</div>
	<div class="col-md-4">
		<h2>Info here</h2>
		<p>
			Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. 
		</p>
		<p>
			<a class="btn btn-default" role="button" href="#">
			View details »

			</a>
		</p>
	</div>
	<div class="col-md-4">
		<h2>Info here</h2>
		<p>
			Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. 
		</p>
		<p>
			<a class="btn btn-default" role="button" href="#">
			View details »

			</a>
		</p>
	</div>
</div>

app/views/urls/new.html.erb
      <div class="jumbotron">
        <h1>Shortyfy me</h1>
        <% @url.errors.each do |attr, msg| %>
			<%= msg %> on <%= attr %>
		<% end %>
        <p class="lead">Add the URL you want to be shortened.</p>
        <p>

		<%= form_for @url do |f| %>
			<p>
				<%= f.label :original %> : <%= f.text_field :original %>
			</p>
			<p>
				<%= f.hidden_field :random_id, :value => @url.random_id %>
			</p>
				<%= f.submit "Shortyfy my URL", class: "btn btn-lg btn-success" %>

		<% end %>
        
      </div>